# Generated by Django 5.1.3 on 2024-12-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='ordenes_archivos/'),
        ),
    ]
