# Generated by Django 5.1.2 on 2024-10-20 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_provedor_remove_productocarrito_carrito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.usuario'),
        ),
    ]
