# Generated by Django 5.1.2 on 2024-10-20 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_reclamo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tienda.usuario'),
        ),
    ]
