# Generated by Django 5.1.2 on 2024-10-20 20:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_reclamo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.CharField(default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='categoria',
            name='prioridad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='fecha_actualizacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productocategoria',
            name='estado',
            field=models.CharField(default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='respuesta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='codigo_seguridad',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
